/*
 * Copyright (c) 2019. Prosit A.S.
 */

import { AuthConfig } from 'angular-oauth2-oidc';
import { environment } from '../../environments/environment';

export const OAuthConfig: AuthConfig = {
  clientId: '2c348fee866eff34be69aa23c8fb879c1c46a605895900b72f49598100ff85aa',
  dummyClientSecret: undefined,
  logoutUrl: new URL('/oauth/revoke', environment.rest).toString(),
  requireHttps: false,
  scope: 'api client',
  tokenEndpoint: new URL('/oauth/token', environment.rest).toString(),
  userinfoEndpoint: new URL('/oauth/info', environment.rest).toString(),
  checkOrigin: false,
  clearHashAfterLogin: false,
  clockSkewInSec: 0,
  customQueryParams: undefined,
  customTokenParameters: [],
  decreaseExpirationBySec: 0,
  disableAtHashCheck: false,
  disableIdTokenTimer: false,
  disablePKCE: false,
  fallbackAccessTokenExpirationTimeInSec: 0,
  issuer: '',
  jwks: undefined,
  loginUrl: '',
  nonceStateSeparator: '',
  oidc: false,
  openUri(uri: string): void {},
  options: undefined,
  postLogoutRedirectUri: '',
  preserveRequestedRoute: false,
  redirectUri: '',
  redirectUriAsPostLogoutRedirectUriFallback: false,
  requestAccessToken: false,
  resource: '',
  responseType: '',
  revocationEndpoint: '',
  rngUrl: '',
  sessionCheckIFrameName: '',
  sessionCheckIFrameUrl: '',
  sessionCheckIntervall: 0,
  sessionChecksEnabled: false,
  showDebugInformation: false,
  silentRefreshIFrameName: '',
  silentRefreshMessagePrefix: '',
  silentRefreshRedirectUri: '',
  silentRefreshShowIFrame: false,
  silentRefreshTimeout: 0,
  siletRefreshTimeout: 0,
  skipIssuerCheck: false,
  skipSubjectCheck: false,
  strictDiscoveryDocumentValidation: false,
  timeoutFactor: 0,
  useHttpBasicAuth: false,
  useIdTokenHintForSilentRefresh: false,
  useSilentRefresh: undefined,
  waitForTokenInMsec: 0,
};
